apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-svc1-deployment
  labels:
    app: svc1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: svc1
  template:
    metadata:
      labels:
        app: svc1
    spec:
      containers:
      - name: svc1
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - "-text={{ .Values.text }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
