apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-svc2-deployment
  labels:
    app: svc2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: svc2
  template:
    metadata:
      labels:
        app: svc2
    spec:
      containers:
      - name: svc2
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - "-text={{ .Values.text }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
